language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build
  - cargo build --release
  - cargo test
  - cargo test --release
  - cargo clippy --all-targets --all-features -- -D warnings -D clippy::all
  - cargo fmt --all -- --check
